name: Build container-based tox-ansible tests

"on":
  workflow_call:
    inputs:
      scenarios:
        required: true
        type: string

jobs:
  container_build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario: ${{ fromJson(inputs.scenarios) }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Update submodules to latest
        run: git submodule update --remote --recursive
      - name: Do install path
        uses: ./tests/.github/actions/install_path/
        id: path
      - name: Install dependencies
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y libapt-pkg-dev build-essential python3-setuptools python3-apt
          python -m pip install --upgrade pip
          pip install -U setuptools wheel
          pip install tox
      - name: Run tox against ${{ matrix.scenario }}
        run: |
          set -ex
          cd "${{ steps.path.outputs.path }}"
          tox -e ${{ matrix.scenario }}
