name: Runs tox-ansible Lint

"on":
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Update git
        run: git submodule update --remote --recursive
      - name: Do install path
        uses: ./tests/.github/actions/install_path/
        id: path
      - name: Install dependencies
        run: python -m pip install --upgrade tox
      - name: Run lint
        run: |
          set -ex
          cd "${{ steps.path.outputs.path }}"
          tox -e lint_all
